name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Release Maven artifacts
        run: |
          mvn release:prepare --batch-mode
          mvn release:perform --batch-mode
        env:
          ACTOR: ${{ secrets.ACTOR }}
          TOKEN: ${{ secrets.TOKEN }}
