name: Deploy Maven Project Kgrill

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Validate POM version
      id: version-check
      run: |
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $CURRENT_VERSION"
        if git describe --tags $(git rev-list --tags --max-count=1) >/dev/null 2>&1; then
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $LATEST_TAG"
          if [ "v$CURRENT_VERSION" == "$LATEST_TAG" ]; then
            echo "Error: Version not bumped. Please update the version in pom.xml."
            exit 1
          fi
        else
          echo "No tags found. Skipping version check."
        fi
        echo "::set-output name=current_version::$CURRENT_VERSION"

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Deploy to GitHub Packages
      env:
        GITHUB_ACTOR: ${{ secrets.ACTOR }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
      run: mvn deploy -DskipTests --settings .github/settings.xml
