name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Increment Version
        run: mvn versions:set -DnewVersion=$(date +%Y%m%d)-$(git rev-parse --short HEAD)

      - name: Copy settings.xml
        run: cp .github/settings.xml $HOME/.m2/settings.xml

      - name: Set environment variables
        run: echo "Setting environment variables"
        env:
          SPRING_APPLICATION_NAME: ${{ secrets.SPRING_APPLICATION_NAME }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }}
          SPRING_JPA_SHOW_SQL: ${{ secrets.SPRING_JPA_SHOW_SQL }}
          LOGGING_LEVEL_ORG_HIBERNATE_SQL: ${{ secrets.LOGGING_LEVEL_ORG_HIBERNATE_SQL }}
          LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL: ${{ secrets.LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL }}

      - name: Build and Deploy to GitHub Packages
        run: |
          mvn clean install -DskipTests
          mvn deploy --settings $HOME/.m2/settings.xml -X
        env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
