name: Publish Package

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - uses: s4u/maven-settings-action@v2.5.0
      with:
        servers: '[{"id": "github","configuration": {"httpHeaders": {"property": {"name": "Authorization","value": "Bearer ${{ secrets.GH_TOKEN }}"}}}}]'

    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn deploy -s .github/settings.xml -X
      env:
        GITHUB_TOKEN: ${{ env.GH_TOKEN }}
