name: Build & Publish Maven Spring Boot Application

on:
  push:
    branches:
      - main  # Adjust branch name as per your main branch
  pull_request:
    branches:
      - main  # Adjust branch name as per your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Build with Maven
      - name: Build Maven project
        run: mvn -B package --file pom.xml

      # Upload JAR artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: target/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Adjust branch name as per your main branch and event trigger

    steps:
      # Download JAR artifact
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: application
          path: target

      # Example: Deploy to GitHub Packages (adjust to your deployment needs)
      - name: Configure GitHub Packages Maven Repository
        run: echo "//maven.pkg.github.com/Taikt08s/kgrill-model/:username=${{ secrets.GH_NAME }}" >> ~/.m2/settings.xml

      - name: Deploy to GitHub Packages
        run: mvn deploy -DskipTests=true --file pom.xml
         
