name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Increment Version
        run: mvn versions:set -DnewVersion=$(date +%Y%m%d)-$(git rev-parse --short HEAD)

      - name: Copy settings.xml
        run: cp .github/settings.xml $HOME/.m2/settings.xml

      - name: Build and Deploy to GitHub Packages
        run: |
          mvn clean install -DskipTests
          mvn deploy --settings $HOME/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ACTOR: ${{ github.actor }}
