name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Deploy to GitHub Packages
        run: mvn clean deploy --settings .github/settings.xml -DskipTests -e -X
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
